; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "CellMate"
#define MyAppVersion "CellMate V1.0"
#define MyAppPublisher "MotionLabratories"
#define MyAppURL "http://www.motionlabratories.com/"
#define MyAppExeName "cm_app.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{E57E075C-9B9B-4558-AA96-1DA35B17198B}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
OutputDir=C:\dv\python\CellMateSetup
OutputBaseFilename=cellmateInstall
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\dv\python\dist\cm_app.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\dist\_hashlib.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\dist\_socket.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\dist\_ssl.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\dist\bz2.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\dist\cm_app.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\dist\library.zip"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\dist\MSVCP90.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\dist\python27.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\dist\select.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\dist\unicodedata.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\dist\w9xpopen.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\dist\wx._controls_.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\dist\wx._core_.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\dist\wx._gdi_.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\dist\wx._grid.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\dist\wx._misc_.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\dist\wx._richtext.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\dist\wx._windows_.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\dist\wxbase28uh_net_vc.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\dist\wxbase28uh_vc.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\dist\wxbase28uh_xml_vc.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\dist\wxmsw28uh_adv_vc.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\dist\wxmsw28uh_core_vc.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\dist\wxmsw28uh_gizmos_vc.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\dist\wxmsw28uh_html_vc.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\dist\wxmsw28uh_richtext_vc.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\cancel_1.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\connect_1.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\exit_1.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\save_1.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\disconnect_1.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\motion.bmp"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\motion_1.bmp"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\motion_2.bmp"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\mico.ICO"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\remove.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\Add.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\dv\python\splash.png"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppName}}"; Filename: "{#MyAppURL}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

